// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

import "ColorSchemes.idl";

namespace Microsoft.Terminal.Settings.Editor
{
    runtimeclass ColorSchemeViewModel : Windows.UI.Xaml.Data.INotifyPropertyChanged, Windows.Foundation.IStringable
    {
        String Name;
        Boolean IsEditable { get; };
        Boolean IsDefaultScheme { get; };

        Boolean RequestRename(String newName);

        // Terminal Colors
        Windows.Foundation.Collections.IVector<ColorTableEntry> NonBrightColorTable;
        Windows.Foundation.Collections.IVector<ColorTableEntry> BrightColorTable;

        ColorTableEntry ColorEntryAt(UInt32 Index);

        // System Colors
        ColorTableEntry ForegroundColor;
        ColorTableEntry BackgroundColor;
        ColorTableEntry CursorColor;
        ColorTableEntry SelectionBackgroundColor;

        // 0 = the scheme states nothing (the profile decides), then 1..4 for
        // AdjustTextMode's Never, Indexed, Always, Automatic in declaration order.
        Int32 AdjustIndistinguishableColorsIndex;

        void DeleteConfirmation_Click(IInspectable sender, Windows.UI.Xaml.RoutedEventArgs args);
        void SetAsDefault_Click(IInspectable sender, Windows.UI.Xaml.RoutedEventArgs args);
        void Duplicate_Click(IInspectable sender, Windows.UI.Xaml.RoutedEventArgs args);
    }

    [default_interface] runtimeclass ColorTableEntry : Windows.UI.Xaml.Data.INotifyPropertyChanged
    {
        String Name { get; };
        IInspectable Tag;
        Windows.UI.Color Color;
        String AccessibleName { get; };
        String NameWithHexCode { get; };
    }
}
